branches:
  only:
    - master
    - devel
    - openfoam-shared-lib
    
environment:
  matrix:

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build:

build_script:
  - md build
  - cd build
  - cmake ../../ 
  - cmake --build . --target ALL_BUILD

matrix:
  fast_finish: true