branches:
  only:
    - master
    - devel
    - openfoam-shared-lib

matrix:
  fast_finish: true

platform:
  - x86
  - x64
configuration:
  - Debug
  - Release

build:
build_script:
  - md build
  - cd build
  - cmake .. 
  - cmake --build . --target ALL_BUILD
  - ctest
